---
- name: Check if docker is running
  command: systemctl status docker
  changed_when: false
  register: docker_status
  failed_when: "'active (running)' not in docker_status.stdout"

- name: Start docker if it's not running
  service:
    name: docker
    state: started
    enabled: yes
  when: docker_status.rc != 0

- name: copy static files to server-static
  command: "docker cp {{ static.path_local }} server-static:{{ static.path_docker }}"